"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenSaleChallenge__factory = exports.Rubixi__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Rubixi__factory_1 = require("./Rubixi__factory");
Object.defineProperty(exports, "Rubixi__factory", { enumerable: true, get: function () { return Rubixi__factory_1.Rubixi__factory; } });
var TokenSaleChallenge__factory_1 = require("./TokenSaleChallenge__factory");
Object.defineProperty(exports, "TokenSaleChallenge__factory", { enumerable: true, get: function () { return TokenSaleChallenge__factory_1.TokenSaleChallenge__factory; } });
